#!/usr/bin/env bash
# Configures my domain zone so that the subdomain www points to your load-balancer IP (lb-01).

query_subdomain_info() {
    local domain="$1"
    local subdomain="$2"

    record_type=$(dig "$subdomain"."$domain" | grep -A1 'ANSWER SECTION:' | tail -n1 | awk '{print $4}')
    IP_address=$(dig "$subdomain"."$domain" | grep -A1 'ANSWER SECTION:' | tail -n1 | awk '{print $5}')

    # Output information
    echo "The subdomain $subdomain is a $record_type record and points to $IP_address"
}

if [[ "$#" == 1 ]]; then
    query_subdomain_info "$1" "www"
    query_subdomain_info "$1" "lb-01"
    query_subdomain_info "$1" "web-01"
    query_subdomain_info "$1" "web-02"
elif [[ "$#" == 2 ]]; then
    query_subdomain_info "$1" "$2"
fi
