#!/usr/bin/env bash

# Script to install Nginx and configure it to return "Hello World!" on the root "/" endpoint,
# and also configures the Nginx server so that /redirect_me is redirecting to another page.

# Update package lists
apt-get update

# Install Nginx
apt-get install -y nginx

# Set up default index page
echo 'Hello World!' > /var/www/html/index.html

# Define the file path for Nginx configuration
file="/etc/nginx/sites-available/default"

# Perform the redirection configuration using sed and save changes to the file
sed -i 's/location \/ {/location \/redirect_me {/; s/try_files $uri $uri\/ =404;/return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;/' "$file"

# Restart Nginx to apply the changes
service nginx restart
