#!/usr/bin/env bash
# Script to install Nginx and configure it to return "Hello World!" on the root "/" endpoint,
# and also configures the Nginx server so that /redirect_me is redirecting to another page.
# The scritp also configures the Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.

# Update package lists
apt-get update

# Install Nginx
apt-get install -y nginx

# Set up default index page
echo 'Hello World!' > /var/www/html/index.html

# Create directory for custom error page
mkdir -p /var/www/error

# Create custom 404 page
echo "Ceci n\x27est pas une page" > /var/www/error/custom_404.html

# Define the file path for Nginx configuration
file="/etc/nginx/sites-available/default"

# Perform the redirection configuration using sed and save changes to the file
sed -i "s/location \/ {/location \/redirect_me {/; s/try_files \$uri \$uri\/ =404;/return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;/" "$file"

# Define the content to append
content='\n\t\terror_page 404 \/custom_404.html; \
        location = \/custom_404.html { \
            root \/var\/www\/error; \
            internal; \
        }'

# Use sed to append the content after the specified text in every location block in the file
sed -i '/^\s\+}/a'\'"$content" "$file"

# Restart Nginx to apply the changes
service nginx restart
