#!/usr/bin/env bash
# Configuration script Nginx web server setup:
# - Installs Nginx
# - Sets up a default 'Hello World!' page on '/'
# - Configures redirection to another page at '/redirect_me'
# - Adds a custom 404 page containing 'Ceci n'est pas une page'
# - Adds a custom HTTP header with 'X-Served-By' as name.

# Update package lists
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Set up default index page
echo 'Hello World!' > /var/www/html/index.html

# Create directory for custom error page
sudo mkdir -p /var/www/error

# Create custom 404 page
echo "Ceci n'est pas une page" > /var/www/error/custom_404.html

# Define the file path for Nginx configuration
file="/etc/nginx/sites-available/default"

# Perform the redirection configuration using sed and save changes to the file
# Modify the Nginx configuration to redirect '/redirect_me' to a YouTube video
sed -i "s/location \/ {/location \/redirect_me {/; s/try_files \$uri \$uri\/ =404;/return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;/" "$file"

# Define the content to append
# The content variable stores the text to be appended to the configuration file.
content='\n\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /var/www/error;\n\t\tinternal;\n\t}'

# Use sed to append the content after the specified text in every location block in the file
# Check if the specified text "error_page 404" is already present in the configuration file.
# If not found, use sed to append the content variable after the closing brace of each location block in the file.
if ! grep -qF "error_page 404" "$file"; then
    sed -i '/^\s\+}/a\'"$content" "$file"
fi

# Add a custom HTTP header
# Check if the custom HTTP header is already present in the configuration file.
# If not found, add the custom HTTP header with the hostname as value.
if ! grep -qF "add_header X-Served-By" "$file"; then
    sed -i "s/root \/var\/www\/html;/root \/var\/www\/html;\n\n\tadd_header X-Served-By $HOSTNAME;/" "$file"
fi

# Restart Nginx to apply the changes
service nginx restart
