#!/usr/bin/env bash
# configures web-02 to be identical to web-01. Installs Nginx, sets up a default 'Hello World!' page on '/', configures 
# redirection to another page at '/redirect_me', adds a custom 404 page containing 'Ceci n'est pas une page' and adds
# a custom HTTP header with 'X-Served-By' as name.

# Update package lists
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Set up default index page
echo 'Hello World!' > /var/www/html/index.html

# Create directory for custom error page
sudo mkdir -p /var/www/error

# Create custom 404 page
echo "Ceci n'est pas une page" > /var/www/error/custom_404.html

# Define the file path for Nginx configuration
file="/etc/nginx/sites-available/default"

# Perform the redirection configuration using sed and save changes to the file
sed -i "s/location \/ {/location \/redirect_me {/; s/try_files \$uri \$uri\/ =404;/return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;/" "$file"

# Define the content to append
content='\n\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /var/www/error;\n\t\tinternal;\n\t}'

# Use sed to append the content after the specified text in every location block in the file
sed -i '/^\s\+}/a\'"$content" "$file"

# Add a custom HTTP header
sed -i "s/root \/var\/www\/html;/root \/var\/www\/html;\n\n\tadd_header X-Served-By $HOSTNAME;/" "$file"

# Restart Nginx to apply the changes
service nginx restart
