#!/usr/bin/env bash
# This script automates the configuration of HAProxy to distribute traffic between web-01 and web-02.

# Update package lists to ensure installation of the latest versions
sudo apt-get update

# Install HAProxy
sudo apt-get install -y haproxy

# Define the HAProxy configuration file
file="/etc/haproxy/haproxy.cfg"

# Define the backend content to be appended
b_content="
backend web-backend
    balance roundrobin
    server 38717-web-01 35.174.211.168:80 check
    server 38717-web-02 54.236.53.244:80 check"

# Append backend configuration if it does not exist in the file
if ! grep -qF "backend web-backend" "$file"; then
    echo "$b_content" >> "$file"
fi

# Define the frontend content to be appended
f_content="
frontend http
    bind *:80
    mode http

    default_backend web-backend"

# Append frontend configuration if it does not exist in the file
if ! grep -qF "frontend http" "$file"; then
    echo "$f_content" >> "$file"
fi

# Restart HAProxy service to apply the configuration changes
sudo service haproxy restart
