#!/usr/bin/env bash
# This script configures the NGINX web server to listen on port 80 instead of 8080.
sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default
service nginx restart
kill -9 "$(cat /run/nginx.pid)"
