#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process.

# Get the PID of the program
id=$(pgrep -f 4-to_infinity_and_beyond)

# Terminate the 4-to_infinity_and_beyond process
if [ -n "$id" ]
then
	kill -15 "$id"
fi
