#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely
# With a 2-second pause between each iteration
# And displays "I am invincible!!!"" when receiving a SIGTERM signal

trap 'echo "I am invincible!!!"' 15
while true
do
    echo "to infinity and beyond"
    sleep 2
done
