#!/usr/bin/env bash
# Displays the contents of the file `/etc/passwd`
# Displays only the username, user id, and user home directory path

while IFS= read -r line;
do
  echo "$line" | cut -d ':' -f 1,3,6
done < "/etc/passwd"
