#!/usr/bin/env bash
# Configures a ufw firewall to block all incoming traffic
#+ except for TCP ports 22, 443 and 80.

sudo apt install ufw
sudo nano /etc/default/ufw
IPV6=yes
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw disable
sudo ufw enable
sudo ufw deny 22/tcp
sudo ufw deny 443/tcp
sudo ufw deny 80/tcp
